# Define a rede customizada para nossos serviços
networks:
  opencontact_internal_network:
    name: opencontact_internal_network
    driver: bridge

# Define os volumes persistentes
volumes:
  postgres_data:

services:
  db:
    image: postgres:17.6-alpine3.22
    container_name: opencontact-db
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - opencontact_internal_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opencontact-api
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - opencontact_internal_network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v1/management/health" ]
      interval: 30s
      timeout: 10s
      retries: 3