# .github/workflows/ci.yml

name: Continuous Integration

on:
  pull_request:
    branches:
      - "main"
      - "develop"
jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: 'x64'

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify