# .github/workflows/ci.yml

name: Continuous Integration

on:
  pull_request:
    branches:
      - "main"
      - "develop"
jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven and run tests
        run: ./mvnw clean install
